# Deploy the site to AWS S3 on a push to specific branches.

name: Deploy Staging - MCP (S3)

on:
  push:
    branches:
    - 'develop'

env:
  NODE: 16
  DOMAIN_STAGING: https://uat.earthdata.nasa.gov/dashboard
  DEPLOY_BUCKET_STAGING: climatedashboard-uat-ieee
  DEPLOY_BUCKET_STAGING_REGION: us-west-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      # See comment on checks.yml - prep step
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: "true"
          submodules: "recursive"

      - name: Use Node.js ${{ env.NODE }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE }}

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: |
            node_modules
            .veda/ui/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}

      - name: Cache dist
        uses: actions/cache@v2
        id: cache-dist
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.workflow }}-${{ github.sha }}

      - name: Install
        run: ./.veda/setup

      - name: Build Staging
        env:
          MAPBOX_TOKEN: ${{secrets.MAPBOX_TOKEN}}
        run: PUBLIC_URL="${{ env.DOMAIN_STAGING }}" yarn stage

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # See comment on checks.yml - prep step
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get submodules
        env:
          SSH_KEY_SUBMODULE: ${{secrets.DELTA_UI_FETCH_KEY}}
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< "${SSH_KEY_SUBMODULE}"; git submodule update --init --recursive
      - name: Restore node_modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: |
            node_modules
            .veda/ui/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}

      - name: Restore dist cache
        uses: actions/cache@v2
        id: cache-dist
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.workflow }}-${{ github.sha }}

      - name: Use Node.js ${{ env.NODE }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE }}

      - name: Serve site from subpath
        run: |
          mkdir deploy/
          mv dist deploy/dashboard
          cp deploy/dashboard/index.html deploy/index.html

      - name: Deploy to S3 Staging
        uses: jakejarvis/s3-sync-action@master
        with:
          # acl is not permitted with current credentials
          # args: --acl public-read --follow-symlinks --delete
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ env.DEPLOY_BUCKET_STAGING }}
          AWS_REGION: ${{ env.DEPLOY_BUCKET_STAGING_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # When serving from a subpath:
          # SOURCE_DIR: ./deploy
          # Otherwise use the build directory directly:
          # SOURCE_DIR: ./dist
          SOURCE_DIR: ./deploy